version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:4.8.2
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_HOST: 127.0.0.1
          
      - image: mysql:5.7

    steps:
      - checkout
      
      - run:
          name: npm-update-install 
          command: sudo npm install -g npm@latest

      - run:
          name: Mysql database
          command: mysql -h 127.0.0.1 -u root -p password -e "create database airjld;"

      - run:
          name: database-setup
          command: npm run db:setup

      - run:
          name: run tests
          command: npm test
          
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'

      - store_artifacts: # special step to save test results as as artifact
          path: test-results.xml
          prefix: tests

      - store_artifacts:
          path: coverage
          prefix: coverage

      - store_test_results: # special step to upload test results for display in Test Summary
          path: test-results.xml  