version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: 'password'
          MYSQL_DATABASE: airjld

    #   - image: mysql:5.7
    #       environment:
    #       MYSQL_ROOT_LOGIN: root
    #       MYSQL_ROOT_PASSWORD: password
    #       MYSQL_HOST: 127.0.0.1

    steps:
      - checkout

      - run: # update npm dependencies
          name: update-npm 
          command: 'sudo npm install -g npm@latest'

      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}

      - run: # install dependencies
          name: install-npm-wee
          command: npm install

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      
    #   - run: # wait for db connection
    #       name: Wait for db
    #       command: dockerize -wait tcp://localhost:3000 -timeout 1m
    
      - run: #connect to mysql and create database 
          name: create database
          command: mysql -u root -p password -e "create database airjld;"

      - run: #setup database with dummy files
          name: seed database
          command: npm run db:setup

      - run: # run tests
          name: test
          command: npm test
          
      - run: # code coverage
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'

      - store_artifacts: # special step to save test results as as artifact
          path: test-results.xml
          prefix: tests

      - store_artifacts:
          path: coverage
          prefix: coverage

      - store_test_results: # special step to upload test results for display in Test Summary
          path: test-results.xml  